server:
  port: 8761

eureka:
  instance:
    hostname: 138.68.144.123
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultUrl: http://${eureka.instance.hostname}:${server.port}/eureka/
