server:
  port: 8761

eureka:
  instance:
    hostname: 164.92.206.217
  client:
    registry-with.eureka: false
    fetch-registry: false
    service-url:
      defaultUrl: https://${eureka.instance.hostname}:${server.port}